name: CI Workflow for React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies securely
        run: npm ci --prefer-offline --no-audit
      
      - name: Lint code with ESLint
        run: npm run lint

      - name: Run tests with Jest
        run: npm test

# Error handling
on:
  workflow_run:
    workflows: ["CI Workflow for React App"]
    types:
      - completed

jobs:
  notify_on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send failure notification
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = github.event.workflow_run;
            const repo = run.repository.full_name;
            const workflow = run.name;
            const actor = run.head_commit.author.name;
            const branch = run.head_branch;
            const runURL = run.html_url;
            github.issues.create({
              repo: repo,
              title: `CI Workflow Failed: ${workflow} on ${branch}`,
              body: `CI Workflow [failed](${runURL}) triggered by ${actor} on branch ${branch}.`
            });

# Security measures
jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies securely
        run: npm ci --prefer-offline --no-audit

      - name: Lint code with ESLint
        run: npm run lint

      - name: Run tests with Jest
        run: npm test

# Performance optimization
jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies securely
        run: npm ci --prefer-offline --no-audit

      - name: Lint code with ESLint
        run: npm run lint

      - name: Run tests with Jest
        run: npm test

      - name: Optimize build for production
        run: npm run build -- --prod

      - name: Analyze bundle size
        run: npm run analyze
